import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SearchComponent from "./components/searchbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Header */}
          <header className="py-4 shadow bg-zinc-950 p-4 border-b border-white">
            <div className="grid grid-rows-2 sm:grid-rows-1 md:grid-rows-1 grid-cols-12 items-center justify-between sm:gap-1">
              {/* Logo */}
              <div className="text-nowrap center text-xl md:text-3xl lg:text-4xl font-extrabold select-none col-start-1 col-end-1 sm:col-start-1 sm:col-end-1 md:col-end-3">
                <div className="origin-center hover:scale-[1.01] transform-gpu">
                  <Link href="/" className=" hover:text-gray-300 text-white ">
                    Fake News
                  </Link>
                </div>

              </div>

              {/* Search Bar */}
              <div className="justify-center row-start-2 sm:row-start-1 self-center col-start-2 col-end-12 sm:col-start-5 md:col-start-5 md:col-end-12 lg:col-start-4 xl:col-start-5 xl:col-end-9">
                <SearchComponent/>
              </div>

              {/* Additional Content (if needed) */}
              <div className="w-1/4"></div>
            </div>
          </header>

          {/* Main Content */}
          <main className="container mx-auto py-4">{children}</main>

          {/* Footer */}
          <footer className=" py-4 mt-auto">
            <div className="container mx-auto text-center text-gray-600 text-sm md:text-sm">
              © {new Date().getFullYear()} Fake News
            </div>
          </footer>
        </div>
      </body>
    </html>);
}
