"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useRouter } from "next/navigation";
import { FormEvent } from "react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter()

  const search = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const formData = new FormData(e.currentTarget);
    const searchTerm = formData.get('article') as string | null;

    if (searchTerm) {
      router.push(`/article/${searchTerm}`)
    }
  };

  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Header */}
          <header className="py-4 shadow bg-zinc-950 p-4 border-b border-white">
  <div className="flex items-center justify-between">
    {/* Logo */}
    <div className="ml-2 text-4xl font-extrabold w-1/4 select-none">
      <Link href="/" className="text-gray-900 hover:text-gray-500 dark:text-white dark:hover:text-gray-00">
        Fake News
      </Link>
    </div>

    {/* Search Bar */}
    <div className="w-full sm:w-1/2 md:w-1/3 flex justify-center">
      <form className="relative w-full" onSubmit={search}>
        <button
          type="submit"
          className="absolute left-2 top-1/2 transform -translate-y-1/2 w-5"
        >
          <FontAwesomeIcon icon={faSearch} className="text-black" />
        </button>
        <input
          type="text"
          name="article"
          placeholder="Search articles..."
          className="w-full pl-10 pr-4 py-2 border rounded-lg text-black"
        />
      </form>
    </div>

    {/* Additional Content (if needed) */}
    <div className="w-1/4"></div>
  </div>
</header>

          {/* Main Content */}
          <main className="container mx-auto py-4">{children}</main>

          {/* Footer */}
          <footer className=" py-4 mt-auto">
            <div className="container mx-auto text-center text-gray-600">
              © {new Date().getFullYear()} Fake News
            </div>
          </footer>
        </div>
      </body>
    </html>);
}
